version: "2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/qchat_app
    links:
      - mongodb
    container_name: qchat_web_1
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    environment:
      PORT: 5000
      SECRET_KEY: "you-will-never-guess"
      DEBUG: 1 # can't pass True here, but 1 works
      MONGODB_DB: "qchat"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: 27017
      UPLOAD_FOLDER: "/qchat_app/static/uploads"
      IMAGES_FOLDER: "/qchat_app/static/images"
      IMAGES_URL: "http://localhost:5000/static/images"
  mongodb:
    image: library/mongo:4.2
    container_name: qchat_mongodb_1
    ports:
      - 27017:27017
